version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn --version
            - run: yarn install
            - run: yarn test
workflows:
  build-and-test:
    jobs:
      - build-and-test
