version: 2.1
orbs:
  node: circleci/node@2.1.1
jobs:
  build-and-test:
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn --version
            - run: yarn install
            - run: yarn test
workflows:
  build-and-test:
    jobs:
      - build-and-test
